apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adminbff
spec:
  selector:
    matchLabels:
      app: adminbff
  replicas: 1
  template:
    metadata:
      labels:
        app: adminbff
    spec:
      containers:
        - name: adminbff
          image: noraimarm/adminbff:latest
          env:
          - name: PORT
            value: "80"
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 0.5
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
