apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: movilbff
spec:
  selector:
    matchLabels:
      app: movilbff
  replicas: 1
  template:
    metadata:
      labels:
        app: movilbff
    spec:
      containers:
        - name: movilbff
          image: noraimarm/movilbff:latest
          env:
          - name: PORT
            value: "80"
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 0.5
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
