apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mscatalogo
spec:
  selector:
    matchLabels:
      app: mscatalogo
  replicas: 2
  template:
    metadata:
      labels:
        app: mscatalogo
    spec:
      containers:
        - name: mscatalogo
          image: noraimarm/mscatalogo:latest
          env:
          - name: PORT
            value: 80
          - name: DB_HOST
            value: http://mysql
          - name: DB_PORT
            value: 80
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 0.4
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1