apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mscatalogo
spec:
  selector:
    matchLabels:
      app: mscatalogo
  replicas: 2
  template:
    metadata:
      labels:
        app: mscatalogo
    spec:
      containers:
        - name: mscatalogo
          image: noraimarm/mscatalogo:v1
          env:
          - name: DB_HOST
            value: http://mysql
          - name: DB_PORT
            value: "3306"
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 0.3
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
