apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: msordenes
spec:
  selector:
    matchLabels:
      app: msordenes
  replicas: 2
  template:
    metadata:
      labels:
        app: msordenes
    spec:
      containers:
        - name: msordenes
          image: noraimarm/msordenes:latest
          env:
          - name: PORT
            value: "80"
          - name: DB_HOST
            value: mongodb
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 0.4
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
