apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: msusuarios
spec:
  selector:
    matchLabels:
      app: msusuarios
  replicas: 2
  template:
    metadata:
      labels:
        app: msusuarios
    spec:
      containers:
        - name: msusuarios
          image: noraimarm/msusuarios:v1
          env:
          - name: PORT
            value: "80"
          - name: DB_HOST
            value: "mongodb"
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 0.4
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
