apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mongo
          image: mysql:latest
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: 
          ports:
          - containerPort: 80